{{- if .Values.aksWorkloadIdentity.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.aksWorkloadIdentity.clientId | quote }}
  labels:
    azure.workload.identity/use: "true"
  name: {{ .Values.aksWorkloadIdentity.serviceAccountName }}
  namespace: {{ .Values.aksWorkloadIdentity.namespace }}
{{- end }}
